In [3]:
import pandas as pd
df=pd.read_csv("advertising.csv",usecols=[1,2,3,4])

In [4]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [7]:
X=df.drop("sales",axis=1)
y=df["sales"]

print(y)
X


0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64


TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [8]:
#statsmodel

In [41]:
import statsmodels.api as sm

In [42]:
lm=sm.OLS(y,X)
model=lm.fit()

In [43]:
model.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Mon, 19 Feb 2024   Prob (F-statistic):                   2.43e-171
Time:                        16:56:14   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [47]:
model.predict(df1)

#scikit learn

0    45.487873
dtype: float64

In [48]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
model=reg.fit(X,y)



In [49]:
model.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [50]:
model.intercept_

2.938889369459412

In [51]:
model.score(X,y)

0.8972106381789522

In [52]:
veri=[[10],[200],[30]]
df1=pd.DataFrame(veri).T
model.predict(df1)

C:\Users\msı\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41.07141442])

In [53]:
from sklearn.metrics import mean_squared_error


In [56]:
MSE=mean_squared_error(model.predict(X),y)
MSE

2.784126314510936

In [57]:
import numpy as np
RMSE=np.sqrt(MSE)
RMSE

1.6685701407225697

In [58]:
#holdout method

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=99)
reg=LinearRegression()
model=reg.fit(X_train,y_train)


In [68]:
model.coef_

array([0.04550574, 0.18820547, 0.00075244])

In [69]:
model.intercept_

2.904485914076922

In [70]:
train_err=np.sqrt(mean_squared_error(model.predict(X_train),y_train))
train_err

1.7236824822650751

In [71]:
test_err=np.sqrt(mean_squared_error(model.predict(X_test),y_test))
test_err

1.431278313830164

In [72]:
from sklearn.model_selection import cross_val_score

In [79]:
#cross-validation MSE
CMSE=np.mean(-cross_val_score(model,X_train,y_train,cv=10,scoring="neg_mean_squared_error"))
CMSE
#eğitim hatası

3.3170289742341246

In [80]:
#cross-validation RMSE
np.sqrt(CMSE)

1.8212712522395242

In [81]:
np.sqrt(np.mean(-cross_val_score(model,X_test,y_test,cv=10,scoring="neg_mean_squared_error")))
#test hatası

1.5797892652529868